### ISSUE TITLE
readme example doesn't compile

### ISSUE THREAD

**Issue by demoray** [yoshuawuyts/exponential-backoff#14]
In the loop `for duration in &backoff { ... }`, duration is of type `Duration`, but later is expected to be `Option<Duration>`.

I _think_ the intent of the example is to do something akin to this, which results in sleeping between iterations, but returning immediately if we are not going to retry:

```rust
let backoff = Backoff::new(retries, min, max);
let mut backoff = backoff.iter();
loop {
    match fs::read_to_string("README.md") {
        Ok(string) => return Ok(string),
        Err(err) => match backoff.next() {
            Some(duration) => thread::sleep(duration),
            None => return Err(err)?,
        },
    }
}
```

If you use `for duration in &backoff` as the example suggestions, you cannot tell if you are going to go through the loop again, which means consumers of the crate will likely always sleep after the last try.  This results in the likely use such as:

```rust
let backoff = Backoff::new(retries, min, max);

for duration in &backoff {
    match fs::read_to_string("README.md") {
        Ok(string) => return Ok(string),
        Err(err) => thread::sleep(duration),
    }
}
bail!("unable to read README.md");
```

**Comment by demoray** [comment]
Another option is to update the iterator to return an `Option<Duration>`.

**Comment by yoshuawuyts** [comment]
@demoray Hey, yeah that's a good catch! I think the best solution here is probably to make the `Iter` type implement `Iterator<Item = Option<Duration>>`. Otherwise there is really no point to it over directly calling [`Backoff::next`](https://docs.rs/exponential-backoff/latest/exponential_backoff/struct.Backoff.html#method.next) in a loop.

Though this is the API we advertise in the README, this isn't exposing today. I think we should fix that and cut a major release to not break any existing builds.
